//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualDebts.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualDebts.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual debts.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current balance.
        /// </summary>
        internal static string CurrentBalance_PageTitle {
            get {
                return ResourceManager.GetString("CurrentBalance_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with name &quot;{0}&quot; already exists..
        /// </summary>
        internal static string EditUsers_AddExistentMsg {
            get {
                return ResourceManager.GetString("EditUsers_AddExistentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not added.
        /// </summary>
        internal static string EditUsers_AddFailedMsg {
            get {
                return ResourceManager.GetString("EditUsers_AddFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string EditUsers_AddUserButton {
            get {
                return ResourceManager.GetString("EditUsers_AddUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user:.
        /// </summary>
        internal static string EditUsers_AddUserLabel {
            get {
                return ResourceManager.GetString("EditUsers_AddUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot consist only of whitespace characters..
        /// </summary>
        internal static string EditUsers_AddWhitespaceMsg {
            get {
                return ResourceManager.GetString("EditUsers_AddWhitespaceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit users.
        /// </summary>
        internal static string EditUsers_PageTitle {
            get {
                return ResourceManager.GetString("EditUsers_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; hasn&apos;t settled all his debts..
        /// </summary>
        internal static string EditUsers_RemoveDebtorMsg {
            get {
                return ResourceManager.GetString("EditUsers_RemoveDebtorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not removed.
        /// </summary>
        internal static string EditUsers_RemoveFailedMsg {
            get {
                return ResourceManager.GetString("EditUsers_RemoveFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string EditUsers_RemoveUserButton {
            get {
                return ResourceManager.GetString("EditUsers_RemoveUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user:.
        /// </summary>
        internal static string EditUsers_RemoveUserLabel {
            get {
                return ResourceManager.GetString("EditUsers_RemoveUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string EditUsers_UserListEmpty {
            get {
                return ResourceManager.GetString("EditUsers_UserListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users:.
        /// </summary>
        internal static string EditUsers_UserListLabel {
            get {
                return ResourceManager.GetString("EditUsers_UserListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MessageBox_OkButton {
            get {
                return ResourceManager.GetString("MessageBox_OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New payment.
        /// </summary>
        internal static string NewPayment_PageTitle {
            get {
                return ResourceManager.GetString("NewPayment_PageTitle", resourceCulture);
            }
        }
    }
}
